from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field
from state.enums import ScoreTrajectory
from state.models import AggregateScores


class TurnEvidence(BaseModel):
    turn_index: int
    excerpt: str
    relevance: str


class FeedbackPoint(BaseModel):
    observation: str
    evidence: list[TurnEvidence] = Field(default_factory=list)
    suggestion: str


class ScoreSummary(BaseModel):
    scores: AggregateScores
    trajectory: ScoreTrajectory
    strongest_dimension: str
    weakest_dimension: str


class TopicCoverageSummary(BaseModel):
    topic: str
    status: str
    turns_spent: int
    peak_depth_score: Optional[int] = None
    summary: str = ""


class TurnInsight(BaseModel):
    """
    Coaching intelligence for a single key turn.
    Generated by the context-intelligence pass (Pass 1.5).
    """
    turn_index: int
    topic: str
    ideal_signals: list[str] = Field(default_factory=list)   # reasoning patterns a strong answer shows
    missing_concepts: list[str] = Field(default_factory=list) # thinking gaps identified
    ideal_answer_outline: str = ""                            # 2-3 sentence directional guidance
    gap_severity: str = "none"                                # "none" | "minor" | "major"


class CoachReport(BaseModel):
    session_id: str
    role: str
    focus_area: str
    total_turns: int
    interview_duration_approx: str

    overall_summary: str
    score_summary: ScoreSummary

    # Role-appropriate display labels for each scoring dimension.
    # Keys are the four dimension names (technical_depth, communication_quality,
    # epistemic_calibration, groundedness); values are role-appropriate labels.
    # Frontend uses these to relabel score bars and strongest/weakest cards.
    dimension_labels: Optional[dict] = None

    strengths: list[FeedbackPoint]
    improvement_areas: list[FeedbackPoint]

    communication_feedback: FeedbackPoint
    technical_feedback: FeedbackPoint
    behavioral_feedback: Optional[FeedbackPoint] = None

    practice_recommendations: list[str] = Field(default_factory=list, max_length=3)
    topic_coverage: list[TopicCoverageSummary]
    transcript_highlights: list[TurnEvidence]

    overall_score: float = 0.0          # Deterministic 0–10 score (never LLM-generated)
    generated_at: str
    prompt_version_coach: str
    weakness_severity: Optional[str] = None  # "none" | "minor" | "significant"

    # ── Coach Intelligence Layer (Pass 1.5) ───────────────────────────────
    # All Optional / defaulted — backwards-compatible with older report dicts.
    turn_insights: list[TurnInsight] = Field(default_factory=list)
    key_missing_concepts: list[str] = Field(default_factory=list)
    role_fit_assessment: str = ""       # 1-2 sentence qualitative role-fit narrative
    role_fit_rating: str = ""           # "strong_fit" | "partial_fit" | "weak_fit"
